import { Room, TimeSlot, UserProfile } from '../types';

// ─── Room Images (Unsplash stable URLs) ───────────────────────────────────────
const IMAGES = {
  lab1: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800&q=80',
  lab2: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
  lab3: 'https://images.unsplash.com/photo-1563207153-f403bf289096?w=800&q=80',
  study1: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=800&q=80',
  study2: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80',
  study3: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80',
  study4: 'https://images.unsplash.com/photo-1506784926709-22f1ec395907?w=800&q=80',
  library1: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&q=80',
  library2: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&q=80',
  library3: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
};

// ─── Mock Rooms ───────────────────────────────────────────────────────────────
export const MOCK_ROOMS: Room[] = [
  // ── Building A3 – Labs ──
  {
    id: 'room-001',
    name: 'Lab A3-101',
    building: 'Building A3',
    location: 'Floor 1, Wing A',
    capacity: 30,
    type: 'lab',
    image: IMAGES.lab1,
    status: 'available',
    floor: '1',
    facilities: ['Projector', 'Air Conditioning', 'Wi-Fi', 'Whiteboard', '30 Computers'],
    description: 'A fully equipped computer lab with high-performance workstations, dual monitors, and a central projector screen.',
  },
  {
    id: 'room-002',
    name: 'Lab A3-202',
    building: 'Building A3',
    location: 'Floor 2, Wing A',
    capacity: 24,
    type: 'lab',
    image: IMAGES.lab2,
    status: 'occupied',
    floor: '2',
    facilities: ['Dual Projectors', 'Air Conditioning', 'Wi-Fi', 'Linux Workstations'],
    description: 'Advanced networking lab with specialized Linux workstations for systems programming and network configuration.',
  },
  {
    id: 'room-003',
    name: 'Lab A3-305',
    building: 'Building A3',
    location: 'Floor 3, Wing A',
    capacity: 20,
    type: 'lab',
    image: IMAGES.lab3,
    status: 'available',
    floor: '3',
    facilities: ['Projector', 'Air Conditioning', 'Wi-Fi', 'Oscilloscopes', 'Electronics Kits'],
    description: 'Electronics and embedded systems lab with oscilloscopes, soldering stations, and prototyping equipment.',
  },
  {
    id: 'room-004',
    name: 'Lab A3-401',
    building: 'Building A3',
    location: 'Floor 4, Wing A',
    capacity: 36,
    type: 'lab',
    image: IMAGES.lab1,
    status: 'available',
    floor: '4',
    facilities: ['Smartboard', 'Air Conditioning', 'Wi-Fi', '36 Computers', 'Scanner'],
    description: 'Large-capacity computer lab with smartboard technology, ideal for workshops and group exercises.',
  },
  {
    id: 'room-005',
    name: 'Lab A3-201',
    building: 'Building A3',
    location: 'Floor 2, Wing B',
    capacity: 16,
    type: 'lab',
    image: IMAGES.lab2,
    status: 'occupied',
    floor: '2',
    facilities: ['Projector', 'Wi-Fi', 'Mac Workstations', 'Wacom Tablets'],
    description: 'Design lab equipped with Mac workstations and Wacom tablets for UI/UX and multimedia projects.',
  },

  // ── Building B2 – Study Rooms ──
  {
    id: 'room-006',
    name: 'Study Room B2-01',
    building: 'Building B2',
    location: 'Floor 1, East Wing',
    capacity: 8,
    type: 'study-room',
    image: IMAGES.study1,
    status: 'available',
    floor: '1',
    facilities: ['Whiteboard', 'Air Conditioning', 'Wi-Fi', 'Power Outlets'],
    description: 'Intimate group study room perfect for small team meetings and collaborative project work.',
  },
  {
    id: 'room-007',
    name: 'Study Room B2-02',
    building: 'Building B2',
    location: 'Floor 1, East Wing',
    capacity: 6,
    type: 'study-room',
    image: IMAGES.study2,
    status: 'available',
    floor: '1',
    facilities: ['Whiteboard', 'Air Conditioning', 'Wi-Fi', 'Monitor Screen'],
    description: 'Small focused study room with a large monitor for presentations and video calls.',
  },
  {
    id: 'room-008',
    name: 'Study Room B2-03',
    building: 'Building B2',
    location: 'Floor 1, West Wing',
    capacity: 12,
    type: 'study-room',
    image: IMAGES.study3,
    status: 'occupied',
    floor: '1',
    facilities: ['Projector', 'Air Conditioning', 'Wi-Fi', 'Whiteboard', 'Round Table'],
    description: 'Medium-sized collaborative room with a round conference table for group discussions.',
  },
  {
    id: 'room-009',
    name: 'Study Room B2-11',
    building: 'Building B2',
    location: 'Floor 1, North Wing',
    capacity: 4,
    type: 'study-room',
    image: IMAGES.study4,
    status: 'available',
    floor: '1',
    facilities: ['Whiteboard', 'Wi-Fi', 'Power Outlets', 'Natural Light'],
    description: 'Cozy 4-person study pod with natural lighting and a calm atmosphere for focused study.',
  },
  {
    id: 'room-010',
    name: 'Study Room B2-21',
    building: 'Building B2',
    location: 'Floor 2, East Wing',
    capacity: 10,
    type: 'study-room',
    image: IMAGES.study1,
    status: 'available',
    floor: '2',
    facilities: ['Smartboard', 'Air Conditioning', 'Wi-Fi', 'Standing Desks'],
    description: 'Modern study room with a smartboard and adjustable standing desks for dynamic work sessions.',
  },
  {
    id: 'room-011',
    name: 'Study Room B2-22',
    building: 'Building B2',
    location: 'Floor 2, West Wing',
    capacity: 8,
    type: 'study-room',
    image: IMAGES.study2,
    status: 'occupied',
    floor: '2',
    facilities: ['Whiteboard', 'Air Conditioning', 'Wi-Fi'],
    description: 'A quiet study space with glass walls and a dedicated whiteboard wall for brainstorming.',
  },
  {
    id: 'room-012',
    name: 'Seminar Room B2-31',
    building: 'Building B2',
    location: 'Floor 3, Main Hall',
    capacity: 50,
    type: 'study-room',
    image: IMAGES.study3,
    status: 'available',
    floor: '3',
    facilities: ['Dual Projectors', 'Air Conditioning', 'Wi-Fi', 'Microphone', 'Recording System'],
    description: 'Large seminar room with audio-visual equipment, suitable for lectures and presentations.',
  },

  // ── Building B2 – More Labs ──
  {
    id: 'room-013',
    name: 'Lab B2-L01',
    building: 'Building B2',
    location: 'Basement, Lab Wing',
    capacity: 20,
    type: 'lab',
    image: IMAGES.lab3,
    status: 'available',
    floor: 'B',
    facilities: ['Projector', 'Air Conditioning', 'Wi-Fi', 'Robotics Equipment'],
    description: 'Robotics and automation lab with servo motors, sensors, and microcontroller kits.',
  },
  {
    id: 'room-014',
    name: 'Lab B2-L02',
    building: 'Building B2',
    location: 'Basement, Lab Wing',
    capacity: 18,
    type: 'lab',
    image: IMAGES.lab1,
    status: 'occupied',
    floor: 'B',
    facilities: ['Projector', 'Air Conditioning', 'Wi-Fi', 'Data Science Workstations', 'GPU Cluster'],
    description: 'High-performance computing lab with GPU clusters for machine learning and data science projects.',
  },

  // ── Library ──
  {
    id: 'room-015',
    name: 'Library Zone A',
    building: 'Main Library',
    location: 'Ground Floor, Zone A',
    capacity: 40,
    type: 'library',
    image: IMAGES.library1,
    status: 'available',
    floor: 'G',
    facilities: ['Wi-Fi', 'Air Conditioning', 'Power Outlets', 'Silent Zone'],
    description: 'The silent study zone of the library, designed for individual deep-focus work.',
  },
  {
    id: 'room-016',
    name: 'Library Zone B',
    building: 'Main Library',
    location: 'Ground Floor, Zone B',
    capacity: 30,
    type: 'library',
    image: IMAGES.library2,
    status: 'available',
    floor: 'G',
    facilities: ['Wi-Fi', 'Air Conditioning', 'Collaborative Tables', 'Whiteboard Panels'],
    description: 'A collaborative open zone in the library with flexible seating and whiteboard panels.',
  },
  {
    id: 'room-017',
    name: 'Library Reading Room',
    building: 'Main Library',
    location: 'Floor 1, Reading Hall',
    capacity: 60,
    type: 'library',
    image: IMAGES.library3,
    status: 'available',
    floor: '1',
    facilities: ['Wi-Fi', 'Air Conditioning', 'Natural Light', 'Quiet Zone', 'Book Access'],
    description: 'The grand reading hall with vaulted ceilings, natural light, and access to the library collection.',
  },
  {
    id: 'room-018',
    name: 'Library Study Pod 1',
    building: 'Main Library',
    location: 'Floor 2, Pods Area',
    capacity: 4,
    type: 'library',
    image: IMAGES.library1,
    status: 'occupied',
    floor: '2',
    facilities: ['Wi-Fi', 'Power Outlets', 'Monitor Screen', 'Soundproofing'],
    description: 'Private soundproofed study pod for focused individual or duo study sessions.',
  },
  {
    id: 'room-019',
    name: 'Library Study Pod 2',
    building: 'Main Library',
    location: 'Floor 2, Pods Area',
    capacity: 4,
    type: 'library',
    image: IMAGES.library2,
    status: 'available',
    floor: '2',
    facilities: ['Wi-Fi', 'Power Outlets', 'Monitor Screen', 'Soundproofing'],
    description: 'Private soundproofed study pod for focused individual or duo study sessions.',
  },
  {
    id: 'room-020',
    name: 'Innovation Hub',
    building: 'Building A3',
    location: 'Floor 5, Rooftop',
    capacity: 25,
    type: 'study-room',
    image: IMAGES.study4,
    status: 'available',
    floor: '5',
    facilities: ['Projector', 'Air Conditioning', 'Wi-Fi', 'Movable Furniture', 'Maker Space'],
    description: 'A dynamic maker space with movable furniture and maker tools for innovation and ideation sessions.',
  },
  {
    id: 'room-021',
    name: 'Lab A3-103',
    building: 'Building A3',
    location: 'Floor 1, Wing B',
    capacity: 28,
    type: 'lab',
    image: IMAGES.lab2,
    status: 'available',
    floor: '1',
    facilities: ['Projector', 'Air Conditioning', 'Wi-Fi', 'Server Racks', 'Network Lab'],
    description: 'Network and server administration lab with dedicated rack servers and Cisco networking equipment.',
  },
  {
    id: 'room-022',
    name: 'Study Hub B2-41',
    building: 'Building B2',
    location: 'Floor 4, Open Space',
    capacity: 20,
    type: 'study-room',
    image: IMAGES.study3,
    status: 'available',
    floor: '4',
    facilities: ['Smartboard', 'Air Conditioning', 'Wi-Fi', 'Lounge Seating', 'Café Corner'],
    description: 'Open collaborative hub with lounge-style seating and a café corner for informal study sessions.',
  },
];

// ─── Time Slots ───────────────────────────────────────────────────────────────
const TODAY = new Date().toISOString().split('T')[0];
const TOMORROW = new Date(Date.now() + 86400000).toISOString().split('T')[0];

function generateSlots(roomId: string, date: string, pattern: SlotStatus[]): TimeSlot[] {
  const times = [
    ['08:00', '09:00'],
    ['09:00', '10:00'],
    ['10:00', '11:00'],
    ['11:00', '12:00'],
    ['13:00', '14:00'],
    ['14:00', '15:00'],
    ['15:00', '16:00'],
    ['16:00', '17:00'],
  ];
  return times.map(([start, end], i) => ({
    id: `slot-${roomId}-${date}-${i}`,
    roomId,
    startTime: start,
    endTime: end,
    date,
    status: pattern[i % pattern.length],
  }));
}

type SlotStatus = 'available' | 'occupied';

const PATTERNS: Record<string, SlotStatus[]> = {
  'room-001': ['available', 'available', 'occupied', 'available', 'available', 'occupied', 'available', 'available'],
  'room-002': ['occupied', 'occupied', 'available', 'occupied', 'occupied', 'available', 'occupied', 'available'],
  'room-003': ['available', 'occupied', 'available', 'available', 'available', 'occupied', 'available', 'occupied'],
  'room-004': ['available', 'available', 'available', 'occupied', 'available', 'available', 'available', 'available'],
  'room-005': ['occupied', 'occupied', 'occupied', 'available', 'occupied', 'available', 'available', 'occupied'],
  'room-006': ['available', 'available', 'occupied', 'available', 'available', 'available', 'occupied', 'available'],
  'room-007': ['available', 'occupied', 'available', 'available', 'occupied', 'available', 'available', 'available'],
  'room-008': ['occupied', 'occupied', 'occupied', 'available', 'available', 'occupied', 'available', 'available'],
  'room-009': ['available', 'available', 'available', 'occupied', 'available', 'available', 'available', 'occupied'],
  'room-010': ['available', 'available', 'available', 'available', 'occupied', 'available', 'available', 'available'],
  'room-011': ['occupied', 'available', 'occupied', 'available', 'occupied', 'available', 'occupied', 'available'],
  'room-012': ['available', 'occupied', 'available', 'occupied', 'available', 'occupied', 'available', 'occupied'],
  'room-013': ['available', 'available', 'occupied', 'available', 'available', 'available', 'occupied', 'available'],
  'room-014': ['occupied', 'occupied', 'available', 'occupied', 'available', 'occupied', 'available', 'occupied'],
  'room-015': ['available', 'available', 'available', 'available', 'available', 'available', 'available', 'available'],
  'room-016': ['available', 'occupied', 'available', 'occupied', 'available', 'available', 'available', 'occupied'],
  'room-017': ['available', 'available', 'occupied', 'available', 'available', 'occupied', 'available', 'available'],
  'room-018': ['occupied', 'occupied', 'occupied', 'occupied', 'available', 'available', 'occupied', 'occupied'],
  'room-019': ['available', 'available', 'available', 'occupied', 'available', 'available', 'occupied', 'available'],
  'room-020': ['available', 'available', 'available', 'available', 'available', 'available', 'available', 'occupied'],
  'room-021': ['available', 'occupied', 'available', 'available', 'occupied', 'available', 'available', 'available'],
  'room-022': ['available', 'available', 'occupied', 'available', 'available', 'occupied', 'available', 'available'],
};

export const MOCK_TIME_SLOTS: TimeSlot[] = MOCK_ROOMS.flatMap((room) => [
  ...generateSlots(room.id, TODAY, PATTERNS[room.id] ?? ['available', 'occupied', 'available', 'available', 'occupied', 'available', 'available', 'available']),
  ...generateSlots(room.id, TOMORROW, PATTERNS[room.id] ?? ['available', 'available', 'occupied', 'available', 'available', 'available', 'occupied', 'available']),
]);

// ─── Mock User ────────────────────────────────────────────────────────────────
export const MOCK_USER: UserProfile = {
  id: 'user-001',
  name: 'Nguyen Van Huy',
  studentId: 'SE180234',
  email: 'huynv.se180234@university.edu.vn',
  faculty: 'Faculty of Information Technology',
  avatarUrl: 'https://i.pravatar.cc/200?img=12',
};
